DROP TABLE IF EXISTS role;
CREATE TABLE ROLE(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NAME VARCHAR(50) UNIQUE);

DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
ROLE_ID INT,
LOGIN VARCHAR(32) UNIQUE,
PASSWORD VARCHAR(60),
EMAIL VARCHAR(50) UNIQUE,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
BIRTHDAY DATE,
PASSWORDAGAIN VARCHAR(60),
FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);